name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  path:
    required: true
    description: 'input description here'
  separator:
    description: 'Separator to differentiate between parts of the path'
    default: '/'
runs:
  using: 'node16'
  main: 'dist/index.js'
